name: HNA Monnitoring and Logging Agent
description: |
  Monnitoring and Logging agent for HNA
version: v0.2
category: HNA
labels:
  io.rancher.certified: rancher
  io.rancher.orchestration.supported: 'cattle'
