version: '2'

services:
  agent:
    image: imikushin/beancounter:v0.3.7
    command: [beancounter, agent]
    environment:
      INFLUXDB_HOST: ${influxdb_host}
    tty: true
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    network_mode: host
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.container.dns: 'true'
